# Generated by Django 3.2.8 on 2021-11-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0006_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmacia',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
